version: '3.9'

services:
  server:
    init: true
    build:
      context: ./
      dockerfile: ./server/Dockerfile

  website:
    init: true
    build:
      context: ./
      dockerfile: ./client/Dockerfile
    links:
      - server
