version: '3.9'

services:
  server:
    restart: unless-stopped
    image: docker.matchbooklab.com/randodex/server:${DOCKER_TAG-latest}
    networks:
      - default

  website:
    restart: unless-stopped
    image: docker.matchbooklab.com/randodex/website:${DOCKER_TAG-latest}
    networks:
      - default
      - proxy # only the container that interfaces with the proxy needs this
    labels:
      traefik.docker.network: pandora_proxy
      traefik.frontend.rule: Host:randodex.com,www.randodex.com
      traefik.enable: true
      traefik.port: 80
      traefik.http.middlewares.test-compress.compress: true

networks:
  default:
  proxy:
    external:
      name: pandora_proxy
